# 1.向量运算

In [3]:
list1 = list(range(10))
list2 = list(range(11,21))
[item1 + item2 for item1, item2 in zip(list1, list2)]

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [4]:
# numpy运算
import numpy as np
list1_arr = np.array(list1)
list2_arr = np.array(list2)
list_sum = list1_arr + list2_arr
print(list_sum)

[11 13 15 17 19 21 23 25 27 29]


# 2.矩阵运算

In [6]:
a = np.array([[1, 2],[3, 4]])
b = np.ones((2, 2))
# 逐元素相乘
print(a * b)
print(np.multiply(a, b))
# 点乘 m,n dot n,1 -> m, 1
c = np.arange(10).reshape(5, 2)
d = np.arange(10).reshape(2, 5)
print(np.dot(c, d).shape)
print((c@d).shape)

[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
(5, 5)
(5, 5)


# 3.matrix相乘

In [7]:
c = np.mat(c)
d = np.mat(d)
print((c*d).shape)  # 此时直接相乘为点乘

(5, 5)


In [11]:
e = np.mat(np.random.random((3, 3))) # 生成3*3随机数矩阵
print('Origin:', e)
print('Inv:', e.I)  # 逆矩阵
print('Transpose:', e.T)  # 转置矩阵
print('Numpy:', e.A)  # 矩阵对应的二维数组

Origin: [[0.65870811 0.49872814 0.88934888]
 [0.75761695 0.49808957 0.94863934]
 [0.08203186 0.13862723 0.03314808]]
Inv: [[-15.12449288  14.04069958   3.96375408]
 [  6.93184338  -6.72337309   6.43262267]
 [  8.43934347  -6.62910514  -6.54308678]]
Transpose: [[0.65870811 0.75761695 0.08203186]
 [0.49872814 0.49808957 0.13862723]
 [0.88934888 0.94863934 0.03314808]]
Numpy: [[0.65870811 0.49872814 0.88934888]
 [0.75761695 0.49808957 0.94863934]
 [0.08203186 0.13862723 0.03314808]]
