# 1.einsum()方法  -爱因斯坦求和约定

- 参数
  - 参数1:格式字符串
    - 格式字符串规定:
    1. 不同的输入变量格式字符之间要用逗号分隔开,且输入格式字符的数量
    要与参数运算的变量数量相匹配.例如,图6-6所示的运算中共输入三个参数
    arg0, arg1和arg2,那么输入格式字符串中就需要有三个用逗号隔开的格式
    字符
    2. 输入格式字符和输出格式字符要用箭头分隔开
    3. 输入格式字符和输出格式字符都是一系列常见字符(如ASCII码)
    4. 格式字符串中的字符数(字符串长度)和张量的维数相对应.如字符串'ij'
    表示二维张量,'ijk'表示三维张量.例如,有如下指令.
    
    result = np.einsum('ijk,ijl->kl',a,b)
    a是一个三维矩阵,因为格式字符串'ijk'是由三个字符构成的.类似地，输入张量b
    也是一个三维矩阵,理由同上.计算结果是一个二维张量，因为箭头后面格式字符串
    'kl'由两个字符构成

In [1]:
import numpy as np
arr =np.arange(10)
print(arr)

# 求和
# 'i->'表示一个一维张量(箭头前面的字符长度为1)
# 箭头后面没有说明维度消失了，变成了一个标量

sum1 = np.einsum('i->', arr) # ASCII码完全不重要，可以写成a->,b->等等
print(sum1)

[0 1 2 3 4 5 6 7 8 9]
45


In [5]:
# 按列求和
arr2 = np.arange(20).reshape(4, 5)
print('arr2: ', arr2)
sum_col = np.einsum('ij->j', arr2)  # i表示行,j表示列
sum_col

arr2:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([30, 34, 38, 42, 46])

In [3]:
# 按行求和
sum_row = np.einsum('ij->i', arr2)
sum_row

array([10, 35, 60, 85])

In [6]:
# 'ijk->jk'  三维变为二维, 按照第一轴求和
# 如果待处理的张量不止三维,将多个维度格式字符串用省略号
# 代替,以表示剩下的所有维度
# result = np.einsum('i...->...', arr)
# 矩阵乘法-点乘
A = np.array([[1, 1, 1],
  [2, 2, 2],
  [5, 5, 5]])

B = np.array([[0, 1, 0],
  [1, 1, 0],
  [1, 1, 1]])

print(A@B)  # 等价于np.dot(A, B)
print(np.einsum('ij,jk->ik', A, B))

[[ 2  3  1]
 [ 4  6  2]
 [10 15  5]]
[[ 2  3  1]
 [ 4  6  2]
 [10 15  5]]


In [9]:
# 向量点乘操作(对应元素乘积) a*b, np.multiply(a,b)
a = np.array([[1,2],[3,4]])
b = np.ones(shape=(2,2))
print('点乘:', np.einsum('ij,ij->ij',a,b)) # 向量点乘
print('内积:', np.einsum('ij,ij->',a,b))  # 内积

点乘: [[1. 2.]
 [3. 4.]]
内积: 10.0


In [11]:
# 求对角线 np.diag(arr)
AA = np.array([[11, 12, 13, 14],
  [21, 22, 23, 24],
  [31, 32, 33, 34],
  [41, 42, 43, 44]])

print(np.einsum('ii->', AA))  # 求矩阵的迹(对角线元素之和)
print(np.einsum('ij->ji',AA)) # 矩阵转置  也可以np.transpose实现

110
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]
 [14 24 34 44]]
